name: Yuweiwei Hugo

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - name: Copy Assets
        run: |
          cp ./assets/icons/* ./themes/assets/icons/
          
      - name: Build
        run: hugo --minify


      - name: Set Domain
        run: |
          cp ./CNAME ./public/CNAME
          echo Domain 設置為 $(cat ./public/CNAME)


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          public_branch: gh-pages  # 推送到 gh-pages 分支
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
